config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :proveedores
  resources :servicios_clicks
  resources :cotizadors
  resources :empresas
  resources :menus

  get 'statick_pages/home'
  get 'statick_pages/help'
  get 'statick_pages/conctact'
 # root  'sessions#new'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  resources :users
end

app/models/proveedore.rb
class Proveedore < ApplicationRecord
end

app/controllers/proveedores_controller.rb
class ProveedoresController < ApplicationController
  before_action :set_proveedore, only: [:show, :edit, :update, :destroy]

  # GET /proveedores
  # GET /proveedores.json
  def index
    @proveedores = Proveedore.all
  end

  # GET /proveedores/1
  # GET /proveedores/1.json
  def show
  end

  # GET /proveedores/new
  def new
    @proveedore = Proveedore.new
  end

  # GET /proveedores/1/edit
  def edit
  end

  # POST /proveedores
  # POST /proveedores.json
  def create
    @proveedore = Proveedore.new(proveedore_params)

    respond_to do |format|
      if @proveedore.save
        format.html { redirect_to @proveedore, notice: 'Proveedore was successfully created.' }
        format.json { render :show, status: :created, location: @proveedore }
      else
        format.html { render :new }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proveedores/1
  # PATCH/PUT /proveedores/1.json
  def update
    respond_to do |format|
      if @proveedore.update(proveedore_params)
        format.html { redirect_to @proveedore, notice: 'Proveedore was successfully updated.' }
        format.json { render :show, status: :ok, location: @proveedore }
      else
        format.html { render :edit }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedores/1
  # DELETE /proveedores/1.json
  def destroy
    @proveedore.destroy
    respond_to do |format|
      format.html { redirect_to proveedores_url, notice: 'Proveedore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proveedore
      @proveedore = Proveedore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proveedore_params
      params.require(:proveedore).permit(:nombre_empresa, :telefono_empresa, :correo_empresa, :nombre_contacto, :telefono_contacto, :correo_contacto)
    end
end

app/helpers/proveedores_helper.rb
module ProveedoresHelper
end

app/views/proveedores/_form.html.erb
<%= form_with(model: proveedore, local: true) do |form| %>
  <% if proveedore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proveedore.errors.count, "error") %> prohibited this proveedore from being saved:</h2>

      <ul>
        <% proveedore.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre_empresa %>
    <%= form.text_field :nombre_empresa %>
  </div>

  <div class="field">
    <%= form.label :telefono_empresa %>
    <%= form.text_field :telefono_empresa %>
  </div>

  <div class="field">
    <%= form.label :correo_empresa %>
    <%= form.text_field :correo_empresa %>
  </div>

  <div class="field">
    <%= form.label :nombre_contacto %>
    <%= form.text_field :nombre_contacto %>
  </div>

  <div class="field">
    <%= form.label :telefono_contacto %>
    <%= form.text_field :telefono_contacto %>
  </div>

  <div class="field">
    <%= form.label :correo_contacto %>
    <%= form.text_field :correo_contacto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proveedores/edit.html.erb
<h1>Editing Proveedore</h1>

<%= render 'form', proveedore: @proveedore %>

<%= link_to 'Show', @proveedore %> |
<%= link_to 'Back', proveedores_path %>

app/views/proveedores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proveedores</h1>

<table>
  <thead>
    <tr>
      <th>Nombre empresa</th>
      <th>Telefono empresa</th>
      <th>Correo empresa</th>
      <th>Nombre contacto</th>
      <th>Telefono contacto</th>
      <th>Correo contacto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proveedores.each do |proveedore| %>
      <tr>
        <td><%= proveedore.nombre_empresa %></td>
        <td><%= proveedore.telefono_empresa %></td>
        <td><%= proveedore.correo_empresa %></td>
        <td><%= proveedore.nombre_contacto %></td>
        <td><%= proveedore.telefono_contacto %></td>
        <td><%= proveedore.correo_contacto %></td>
        <td><%= link_to 'Show', proveedore %></td>
        <td><%= link_to 'Edit', edit_proveedore_path(proveedore) %></td>
        <td><%= link_to 'Destroy', proveedore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proveedore', new_proveedore_path %>

app/views/proveedores/new.html.erb
<h1>New Proveedore</h1>

<%= render 'form', proveedore: @proveedore %>

<%= link_to 'Back', proveedores_path %>

app/views/proveedores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre empresa:</strong>
  <%= @proveedore.nombre_empresa %>
</p>

<p>
  <strong>Telefono empresa:</strong>
  <%= @proveedore.telefono_empresa %>
</p>

<p>
  <strong>Correo empresa:</strong>
  <%= @proveedore.correo_empresa %>
</p>

<p>
  <strong>Nombre contacto:</strong>
  <%= @proveedore.nombre_contacto %>
</p>

<p>
  <strong>Telefono contacto:</strong>
  <%= @proveedore.telefono_contacto %>
</p>

<p>
  <strong>Correo contacto:</strong>
  <%= @proveedore.correo_contacto %>
</p>

<%= link_to 'Edit', edit_proveedore_path(@proveedore) %> |
<%= link_to 'Back', proveedores_path %>