config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :proveedores
  resources :servicios_clicks
  resources :cotizadors
  resources :empresas
  resources :menus

  get 'statick_pages/home'
  get 'statick_pages/help'
  get 'statick_pages/conctact'
 # root  'sessions#new'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  resources :users
end

app/models/cotizador.rb
class Cotizador < ApplicationRecord
    validates :nombre_cliente, presence: true, length: { maximum: 150 }
    validates :servisios, presence: true, length: { maximum: 11}
    validates :email, presence: true, length: { maximum: 120}
    validates :telefono, presence: true, length: { maximum: 15}
    
     
end

app/controllers/cotizadors_controller.rb
class CotizadorsController < ApplicationController
  before_action :set_cotizador, only: [:show, :edit, :update, :destroy]

  # GET /cotizadors
  # GET /cotizadors.json
  def index
       if logged_in?
    @cotizadors = Cotizador.all
       else
         redirect_to login_url
       end
  end

  # GET /cotizadors/1
  # GET /cotizadors/1.json
  def show
  end

  # GET /cotizadors/new
  def new
    @cotizador = Cotizador.new
  end

  # GET /cotizadors/1/edit
  def edit
  end

  # POST /cotizadors
  # POST /cotizadors.json
  def create
    @cotizador = Cotizador.new(cotizador_params)

    respond_to do |format|
      if @cotizador.save
        format.html { redirect_to @cotizador, notice: 'Cotizador was successfully created.' }
        format.json { render :show, status: :created, location: @cotizador }
      else
        format.html { render :new }
        format.json { render json: @cotizador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cotizadors/1
  # PATCH/PUT /cotizadors/1.json
  def update
    respond_to do |format|
      if @cotizador.update(cotizador_params)
        format.html { redirect_to @cotizador, notice: 'Cotizador was successfully updated.' }
        format.json { render :show, status: :ok, location: @cotizador }
      else
        format.html { render :edit }
        format.json { render json: @cotizador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cotizadors/1
  # DELETE /cotizadors/1.json
  def destroy
    @cotizador.destroy
    respond_to do |format|
      format.html { redirect_to cotizadors_url, notice: 'Cotizador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cotizador
      @cotizador = Cotizador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cotizador_params
      params.require(:cotizador).permit(:nombre_cliente, :servisios, :comentario, :email, :telefono, :direccion)
    end
end

app/helpers/cotizadors_helper.rb
module CotizadorsHelper
end

app/views/cotizadors/_form.html.erb
    <div class="row" >
        <div class="col-md-1 col-md-offset-3"></div>
<div class="col-md-10 col-md-offset-3 card cardform">
<%= form_with(model: cotizador, local: true) do |form| %>
  <% if cotizador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cotizador.errors.count, "error") %> prohibited this cotizador from being saved:</h2>

      <ul>
        <% cotizador.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre_completo %>
    <%= form.text_field :nombre_cliente , class: 'form-control'%>
  </div>

  <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email , class: 'form-control'%>
    </div>
  
    <div class="field">
      <%= form.label :telefono %>
      <%= form.text_field :telefono , class: 'form-control'%>
    </div>
  
    <div class="field">
      <%= form.label :direccion %>
      <%= form.text_field :direccion , class: 'form-control'%>
    </div>

  <div class="field">
    <%= form.label :servicios %>
      <%= form.select( :servisios , ServiciosClick.all.collect { |s| [ s.nombre , s.id ] },  { class: "form-control"} ) %>
  </div>

  <div class="field">
    <%= form.label :comentario %>
    <%= form.text_area :comentario , class: 'form-control'%>
  </div>

 <br/>
<br/>
  <div class="actions">
    <%= form.submit "Solisita Tu cotizacion de imedato", class: "form-control btn btn-primary" %>
  </div>
<% end %>
<br>
</div>
<div class="col-md-1 col-md-offset-3"></div>
</div>

app/views/cotizadors/edit.html.erb
<h1>Editing Cotizador</h1>

<%= render 'form', cotizador: @cotizador %>

<%= link_to 'Show', @cotizador %> |
<%= link_to 'Back', cotizadors_path %>

app/views/cotizadors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cotizadors</h1>

<table  class="table">
  <thead class="thead-dark">
    <tr>
      <th>Nombre cliente</th>
      <th>Servisios</th>
      <th>Comentario</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cotizadors.each do |cotizador| %>
      <tr>
        <td><%= cotizador.nombre_cliente %></td>
        <td><%= cotizador.servisios %></td>
        <td><%= cotizador.comentario %></td>
        <td><%= cotizador.email %></td>
        <td><%= cotizador.telefono %></td>
        <td><%= cotizador.direccion %></td>
        <td><%= link_to 'Show', cotizador %></td>
        <td><%= link_to 'Edit', edit_cotizador_path(cotizador) %></td>
        <td><%= link_to 'Destroy', cotizador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cotizador', new_cotizador_path %>

app/views/cotizadors/new.html.erb
<h1 class="title">Cotiza tu proyecto a qui.</h1>

<%= render 'form', cotizador: @cotizador %>
<% if logged_in? %>  
<%= link_to 'Back', cotizadors_path %>
<% else %>
<%= link_to 'Back', login_url %>
<% end %>

app/views/cotizadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre cliente:</strong>
  <%= @cotizador.nombre_cliente %>
</p>

<p>
  <strong>Servisios:</strong>
  <%= @cotizador.servisios %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @cotizador.comentario %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cotizador.email %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @cotizador.telefono %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @cotizador.direccion %>
</p>

<%= link_to 'Edit', edit_cotizador_path(@cotizador) %> |
<%= link_to 'Back', cotizadors_path %>