config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :proveedores
  resources :servicios_clicks
  resources :cotizadors
  resources :empresas
  resources :menus

  get 'statick_pages/home'
  get 'statick_pages/help'
  get 'statick_pages/conctact'
 # root  'sessions#new'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
  resources :users
end

app/models/servicios_click.rb
class ServiciosClick < ApplicationRecord
end

app/controllers/servicios_clicks_controller.rb
class ServiciosClicksController < ApplicationController
  before_action :set_servicios_click, only: [:show, :edit, :update, :destroy]

  # GET /servicios_clicks
  # GET /servicios_clicks.json
  def index
    @servicios_clicks = ServiciosClick.all
  end

  # GET /servicios_clicks/1
  # GET /servicios_clicks/1.json
  def show
  end

  # GET /servicios_clicks/new
  def new
    @servicios_click = ServiciosClick.new
  end

  # GET /servicios_clicks/1/edit
  def edit
  end

  # POST /servicios_clicks
  # POST /servicios_clicks.json
  def create
    @servicios_click = ServiciosClick.new(servicios_click_params)

    respond_to do |format|
      if @servicios_click.save
        format.html { redirect_to @servicios_click, notice: 'Servicios click was successfully created.' }
        format.json { render :show, status: :created, location: @servicios_click }
      else
        format.html { render :new }
        format.json { render json: @servicios_click.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicios_clicks/1
  # PATCH/PUT /servicios_clicks/1.json
  def update
    respond_to do |format|
      if @servicios_click.update(servicios_click_params)
        format.html { redirect_to @servicios_click, notice: 'Servicios click was successfully updated.' }
        format.json { render :show, status: :ok, location: @servicios_click }
      else
        format.html { render :edit }
        format.json { render json: @servicios_click.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios_clicks/1
  # DELETE /servicios_clicks/1.json
  def destroy
    @servicios_click.destroy
    respond_to do |format|
      format.html { redirect_to servicios_clicks_url, notice: 'Servicios click was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servicios_click
      @servicios_click = ServiciosClick.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servicios_click_params
      params.require(:servicios_click).permit(:nombre, :descripcion, :url_imagen)
    end
end

app/helpers/servicios_clicks_helper.rb
module ServiciosClicksHelper
end

app/views/servicios_clicks/_form.html.erb
<%= form_with(model: servicios_click, local: true) do |form| %>
  <% if servicios_click.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(servicios_click.errors.count, "error") %> prohibited this servicios_click from being saved:</h2>

      <ul>
        <% servicios_click.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :url_imagen %>
    <%= form.text_field :url_imagen %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/servicios_clicks/edit.html.erb
<h1>Editing Servicios Click</h1>

<%= render 'form', servicios_click: @servicios_click %>

<%= link_to 'Show', @servicios_click %> |
<%= link_to 'Back', servicios_clicks_path %>

app/views/servicios_clicks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Servicios Clicks</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Url imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servicios_clicks.each do |servicios_click| %>
      <tr>
        <td><%= servicios_click.nombre %></td>
        <td><%= servicios_click.descripcion %></td>
        <td><%= servicios_click.url_imagen %></td>
        <td><%= link_to 'Show', servicios_click %></td>
        <td><%= link_to 'Edit', edit_servicios_click_path(servicios_click) %></td>
        <td><%= link_to 'Destroy', servicios_click, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Servicios Click', new_servicios_click_path %>

app/views/servicios_clicks/new.html.erb
<h1>New Servicios Click</h1>

<%= render 'form', servicios_click: @servicios_click %>

<%= link_to 'Back', servicios_clicks_path %>

app/views/servicios_clicks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @servicios_click.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @servicios_click.descripcion %>
</p>

<p>
  <strong>Url imagen:</strong>
  <%= @servicios_click.url_imagen %>
</p>

<%= link_to 'Edit', edit_servicios_click_path(@servicios_click) %> |
<%= link_to 'Back', servicios_clicks_path %>